FROM node:latest

WORKDIR /usr/src/app

# Install app dependencies by copying package.json and package-lock.json
COPY ./frontend/package*.json ./

RUN npm install

COPY ./frontend .

EXPOSE 3000

CMD ["npm", "start"]