# Generated by Django 4.2.9 on 2024-02-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="subject",
            field=models.CharField(default="default", max_length=120),
            preserve_default=False,
        ),
    ]
