# Generated by Django 4.2.10 on 2024-02-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0003_journalentry_journalentrycontent_delete_journal"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="title",
            field=models.CharField(default="Default Journal Title", max_length=120),
            preserve_default=False,
        ),
    ]
