# Generated by Django 4.2.10 on 2024-02-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_app", "0004_journalentry_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journalentrycontent",
            old_name="entry",
            new_name="entry_id",
        ),
    ]
